version: '2'
volumes:
  harbor_adminserver:
    external: true
    driver: ${volumedriver}
  harbor_jobservice:
    external: true
    driver: ${volumedriver}
  harbor_registry:
    external: true
    driver: ${volumedriver}
  harbor_ui:
    external: true
    driver: ${volumedriver}
services:
  setupswrapper:
    image: chuckey/harbor-setupswrapper:v1.2.2
    container_name: setupswrapper
    restart: always
    volumes:
      -harbor_adminserver:/etc/adminserver
      -harbor_jobservice:/etc/jobservice
      -harbor_registry:/etc/registry
      -harbor_ui:/etc/ui
    environment:
      - REGISTRY_CONFIG=${registry_config}
    command: ["/harbor/harbor-setupswrapper.sh"]
    network_mode: "none"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  registry:
    image: vmware/registry:2.6.2-photon
    container_name: registry
    restart: always
    volumes:
      - harbor_registry:/etc/registry
      - ${data_registry}:/storage
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    links:
      - setupswrapper
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  adminserver:
    image: vmware/harbor-adminserver:v1.2.2
    container_name: harbor-adminserver
    restart: always
    environment:
      - LOG_LEVEL=debug
      - EXT_ENDPOINT=https://${harborhostname}
      - AUTH_MODE=${auth_mode}
      - SELF_REGISTRATION=on
      - LDAP_URL=${ldap_url}
      - LDAP_BASE_DN=${ldap_basedn}
      - LDAP_SEARCH_DN=${ldap_searchdn}
      - LDAP_SEARCH_PWD=${ldap_search_pwd}
      - LDAP_UID=uid
      - LDAP_SCOPE=3
      - LDAP_TIMEOUT=5
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USR=root
      - MYSQL_PWD=${db_password}
      - MYSQL_DATABASE=registry
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://ui/service/token
      - HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - VERIFY_REMOTE_CERT=on
      - MAX_JOB_WORKERS=5
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - TOKEN_EXPIRATION=30
      - CFG_EXPIRATION=5
      - GODEBUG=netdns=cgo
      - PROJECT_CREATION_RESRICTION=everyone
    volumes:
      - harbor_adminserver:/etc/adminserver
      - ${data_registry}:/data
    links:
      - setupswrapper
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  ui:
    image: vmware/harbor-ui:v1.2.2
    container_name: harbor-ui
    restart: always
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/etc/ui/app.conf
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
    volumes:
      - harbor_ui:/etc/ui
    links:
      - setupswrapper
      - adminserver
      - registry
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  jobservice:
    image: vmware/harbor-jobservice:v1.2.2
    container_name: harbor-jobservice
    restart: always
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/etc/jobservice/app.conf
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
    volumes:
      - harbor_jobservice:/etc/jobservice
    links:
      - setupswrapper
      - adminserver
      - ui
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
     io.rancher.container.hostname_override: container_name
  mysql:
    image: rancher/external-service

