version: '2'
volumes:
  adminserver:
    external: true
    driver: ${volumedriver}
    driver_opts:
      exportBase: /nfs/harbor
  jobservice:
    external: true
    driver: ${volumedriver}
    driver_opts:
      exportBase: /nfs/harbor
  registry:
    external: true
    driver: ${volumedriver}
    driver_opts:
      exportBase: /nfs/harbor
  ui:
    external: true
    driver: ${volumedriver}
    driver_opts:
      exportBase: /nfs/harbor
services:
  registry:
    image: vmware/registry:2.6.2-photon
    container_name: registry
    restart: always
    volumes:
      - registry:/etc/registry
      - ${data_registry}:/storage
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      #io.rancher.scheduler.affinity:host_label: ${harborhostlabel}
      io.rancher.container.hostname_override: container_name
  adminserver:
    image: vmware/harbor-adminserver:v1.2.2
    container_name: harbor-adminserver
    restart: always
    environment:
      - LOG_LEVEL=debug
      - EXT_ENDPOINT=https://${harborhostname}
      - AUTH_MODE=${auth_mode}
      - SELF_REGISTRATION=on
      - LDAP_URL=${ldap_url}
      - LDAP_BASE_DN=${ldap_basedn}
      - LDAP_SEARCH_DN=${ldap_searchdn}
      - LDAP_SEARCH_PWD=${ldap_search_pwd}
      - LDAP_UID=uid
      - LDAP_SCOPE=3
      - LDAP_TIMEOUT=5
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USR=root
      - MYSQL_PWD=${db_password}
      - MYSQL_DATABASE=registry
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://ui/service/token
      - HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - VERIFY_REMOTE_CERT=on
      - MAX_JOB_WORKERS=5
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - TOKEN_EXPIRATION=30
      - CFG_EXPIRATION=5
      - GODEBUG=netdns=cgo
    volumes:
      - adminserver:/etc/adminserver
      - ${data_registry}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  ui:
    image: vmware/harbor-ui:v1.2.2
    container_name: harbor-ui
    restart: always
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/etc/ui/app.conf
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
    volumes:
      - ui:/etc/ui
    links:
      - adminserver
      - registry
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  jobservice:
    image: vmware/harbor-jobservice:v1.2.2
    container_name: harbor-jobservice
    restart: always
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/etc/jobservice/app.conf
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
    volumes:
      - jobservice:/etc/jobservice
    links:
      - adminserver
      - ui
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
     io.rancher.container.hostname_override: container_name
  mysql:
    image: rancher/external-service

