version: '2'
services:
  registry:
    image: vmware/registry:2.6.2-photon
    container_name: registry
    restart: always
    volumes:
      - ${data_registry}:/storage
    environment:
      - GODEBUG=netdns=cgo
    secrets:
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: registry-config.yml
        target: "config.yml"
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: registry-root.crt
        target: "root.crt"
    command:
      ["serve", "/run/secrets/config.yml"]
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  adminserver:
    image: vmware/harbor-adminserver:v1.2.2
    container_name: harbor-adminserver
    restart: always
    environment:
      - LOG_LEVEL=debug
      - EXT_ENDPOINT=https://${harborhostname}
      - AUTH_MODE=${auth_mode}
      - SELF_REGISTRATION=on
      - LDAP_URL=${ldap_url}
      - LDAP_BASE_DN=${ldap_basedn}
      - LDAP_SEARCH_DN=${ldap_searchdn}
      - LDAP_SEARCH_PWD=${ldap_search_pwd}
      - LDAP_UID=uid
      - LDAP_SCOPE=3
      - LDAP_TIMEOUT=5
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USR=root
      - MYSQL_PWD=${db_password}
      - MYSQL_DATABASE=registry
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://ui/service/token
      - HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - VERIFY_REMOTE_CERT=on
      - MAX_JOB_WORKERS=5
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - TOKEN_EXPIRATION=30
      - CFG_EXPIRATION=5
      - GODEBUG=netdns=cgo
      - PROJECT_CREATION_RESTRICTION=everyone
      - KEY_PATH=/run/secrets/key
    volumes:
      - ${data_registry}:/data
    secrets:
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: key
        target: 'key'
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  ui:
    image: chuckey/harbor-ui:v1.2.2
    container_name: harbor-ui
    restart: always
    environment:
      - LOG_LEVEL=debug
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
      - KEY_PATH=/run/secrets/key
      - CONFIG_PATH=/run/secrets/app.conf
    secrets:
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: key
        target: "key"
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: ui-app.conf
        target: "app.conf"
    links:
      - adminserver
      - registry
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
  jobservice:
    image: vmware/harbor-jobservice:v1.2.2
    container_name: harbor-jobservice
    restart: always
    environment:
      - LOG_LEVEL=debug
      - UI_SECRET=HvfmjXymGJsmtLaD
      - JOBSERVICE_SECRET=txY9rX6x62qyvYXu
      - GODEBUG=netdns=cgo
      - KEY_PATH=/run/secrets/key
      - CONFIG_PATH=/run/secrets/app.conf
    secrets:
      - mode: '0444'
        uid: '0'
        gid: '0'
        source: jobservice-app.conf
        target: "app.conf"
    links:
      - adminserver
      - ui
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
     io.rancher.container.hostname_override: container_name
  mysql:
    image: rancher/external-service

