version: '2'
.catalog:
  name: Harbor
  version: v1.2.2
  description: |
    Enterprise Class Container Registry [by VMware]
  minimum_rancher_version: v1.2.2
  uuid: harbor-4
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: registry.example.com
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "db_address"
      label: "Harbor database ip address:"
      description: |
        Harbor database ip address
      default: 1.1.1.1
      required: true
      type: "string"
    - variable: "db_password"
      label: "Harbor database password:"
      description: |
        Harbor database password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "ldap_url"
      label: "url for ldap auth:"
      description: |
        Endpoint for ldap auth
      default: example.ldap.com
      required: true
      type: "string"
    - variable: "ldap_basedn"
      label: "basedn for ldap search:"
      description: |
        Basedn for ldap search
      default: dc=domain,dc=com
      required: true
      type: "string"
    - variable: "ldap_searchdn"
      label: "searchdn for ldap auth:"
      description: |
        Searchdn for ldap auth
      default: uid=searchuser,ou=people,dc=domain,dc=com
      required: true
      type: "string"
    - variable: "ldap_search_pwd"
      label: "password for ldap searchdn:"
      description: |
        Password for ldap searchdn
      default: xxxxxx
      required: true
      type: "string"
#    - variable: "harborhostlabel"
#      label: "Harbor will be deployed on the host(s) with this label (default: harbor-host=true)"
#      description: |
#        The various Harbor containers will be deployed on host(s) with this label
#        Set the label on one host if you want Harbor to be deployed on a single host (rancher-nfs volume driver is required for multiple hosts)
#      default: harbor-host=true
#      required: true
#      type: "string"
#    - variable: "harborlbhostlabel"
#      label: "Rancher load balancer will be deployed on the host(s) with this label (default: harbor-lb-host=true)"
#      description: |
#        The Rancher load balancer will be deployed on host(s) with this label
#        Make sure you understand the pre-requisite as outlined in the README document above
#      default: harbor-lb-host=true
#      required: true
#      type: "string"
    - variable: "volumedriver"
      description: "Volume Driver being used. Set rancher-nfs if you run in distributed mode"
      label: "Volume Driver:"
      required: true
      default: rancher-nfs
      type: "enum"
      options:
      #  - local
        - rancher-nfs
    - variable: "auth_mode"
      description: "Harbor auth mode"
      label: "Auth Mode:"
      required: true
      default: db_auth
      type: "enum"
      options:
        - db_auth
        - ldap_auth
    - variable: "private_key"
      description: "Harbor private key for general token:"
      label: "Private Key:"
      required: true
      type: "multiline"
    - variable: "public_key"
      description: "Harbor public key for verify token:"
      label: "Public Key:"
      required: true
      type: "multiline"
    - variable: "config"
      description: "Harbor registry config.yml:"
      label: "Config:"
      required: true
      type: "multiline"
    - variable: "data_registry"
      description: "Harbor registry storage path:(only for filesystem storage in config.yml)"
      label: "StoragePath:"
      required: true
      type: "string"
services:
  registry:
    scale: 1
  adminserver:
    scale: 1
  harbor-lb:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 8080
        target_port: 80
        path: /
        hostname: ${harborhostname}
        service: ui
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  jobservice:
    scale: 1
  ui:
    scale: 1
  harbor-setupwrapper:
    scale: 1
  mysql:
    scale: 1
    external_ips:
    - ${db_address}
    health_check:
      port: 3306
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      interval: 2000
