version: '2'
services:
  vault:
    image: registry.sensetime.com/sre/vault:0.9.1
    container_name: vault
    restart: always
    extra_hosts:
      - "vault.sensetime.com:127.0.0.1"
    command:
      - /bin/sh
      - c
      - mkdir -p /etc/vault && cp /run/secrets/* /etc/vault/
      - run.sh
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: vault-auto-unsealer
  vault-auto-unsealer:
    image: registry.sensetime.com/sre/vault-auto-unsealer:0.9.1
    container_name: vault-auto-unsealer
    network_mode: container:vault
    volumes_from:
      - vault
    command:
      ["master"]
    links:
      - vault
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  vault-ui:
    image: registry.sensetime.com/sre/vault-ui:v1
    container_name: vault-ui
    restart: always
    environment:
      - VAULT_URL_DEFAULT=http://vault.sensetime.com:8200
      - VAULT_AUTH_DEFAULT=LDAP
    links:
      - vault:vault.sensetime.com
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
