version: '2'
volumes: #most volumes mappings require optimization (now all volumes map all containers)
  vault:
    external: true
    driver: ${volumedriver}
services:
  setupswrapper:
    image: registry.sensetime.com/sre/vault-setupswrapper:0.9.1
    container_name: setupswrapper
    environment:
      - CONFIG=${config}
      - CERTIFICATE_KEY=${certificate_key}
      - CERTIFICATE_CRT=${certificate_crt}
    volumes:
      - vault:/etc/vault
    network_mode: "none"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  vault:
    image: registry.sensetime.com/sre/vault:0.9.1
    container_name: vault
    restart: always
    volumes:
      - vault:/etc/vault
    links:
      - setupswrapper
    extra_hosts:
      - "vault.sensetime.com:127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: vault-auto-unsealer
  vault-auto-unsealer:
    image: registry.sensetime.com/sre/vault-auto-unsealer:0.9.1
    container_name: vault-auto-unsealer
    network_mode: container:vault
    volumes_from:
      - vault
    command:
      ["master"]
    links:
      - setupswrapper
      - vault
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  vault-ui:
    image: registry.sensetime.com/sre/vault-ui:v1
    container_name: vault-ui
    restart: always
    environment:
      - VAULT_URL_DEFAULT=http://vault.sensetime.com:8200
      - VAULT_AUTH_DEFAULT=LDAP
    links:
      - vault:vault.sensetime.com
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    labels:
      io.rancher.container.hostname_override: container_name
