version: '2'
.catalog:
  name: Vault
  version: 0.9.1
  description: |
    Enterprise Secret Manager [by Hashicorp]
  minimum_rancher_version: 0.9.1
  uuid: vault-1
services:
  vault:
    scale: 1
  vault-ui:
    scale: 1
